name:                draigana
version:             0.1.0.0
github:              jegp/draigana
license:             GPLv3
author:              Jens Egholm Pedersen
maintainer:          jensegholm@protonmail.com
copyright:           2017 Jens Egholm Pedersen

extra-source-files:
- README.md

# Metadata used when publishing your package
synopsis:            AI for playing the game draigana
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/draigana#readme>

dependencies:
- base >= 4.7 && < 5
- containers >= 0.5.10.2

library:
  source-dirs: src

executables:
  play-par:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - draigana

  play-seq:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -rtsopts
    dependencies:
    - draigana

tests:
  spec:
    source-dirs: test
    main: Spec.hs
    dependencies:
      - draigana
      - hspec == 2.*
      - QuickCheck

ghc-options:
  - -O3
